#ifndef PINSALOC_H_
#define PINSALOC_H_

#define WHEEL_ENCODER_LEFT_PIN 5
#define WHEEL_LEFT_PWN_PIN 4
#define WHEEL_LEFT_OUT_PIN_1 2
#define WHEEL_LEFT_OUT_PIN_2 3

#define WHEEL_ENCODER_RIGHT_PIN 7
#define WHEEL_RIGHT_PWN_PIN 6
#define WHEEL_RIGHT_OUT_PIN_1 8
#define WHEEL_RIGHT_OUT_PIN_2 9

#define BUZZER_PIN 18
#define TRIG_PIN 0
#define ECHO_PIN 1

#endif